//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeology.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public int attachment_id { get; set; }
        public Nullable<int> deal_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public byte[] attachment1 { get; set; }
        public string caption { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
