//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeology.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealByContact
    {
        public int ID { get; set; }
        public int deal_by_contact_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> deal_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
