//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeology.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ID { get; set; }
        public int user_id { get; set; }
        public string message { get; set; }
        public string stacktrace { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
