//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeology.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public int message_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> deal_id { get; set; }
        public string message1 { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
    }
}
