//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homeology.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wishlist()
        {
            this.WishlistItems = new HashSet<WishlistItem>();
        }
    
        public int ID { get; set; }
        public int wishlist_id { get; set; }
        public Nullable<int> deal_id { get; set; }
        public Nullable<System.DateTime> target_date { get; set; }
        public string target_price { get; set; }
        public string target_coord { get; set; }
    
        public virtual Deal Deal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishlistItem> WishlistItems { get; set; }
    }
}
